baseURL = "http://example.org/"
languageCode = "en-us"
# title = "Event loop software"
theme = "ananke"
# sectionPagesMenu = "main"


[params]
  favicon = ""
  site_logo = ""
  # description = "The last theme you'll ever need. Maybe."
  twitter = "https://twitter.com/hielkedv"
  github = "https://github.com/frevib"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/hielkedv/"
  #mastodon = ""
  #slack = ""
  # stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-green"
  #featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 0
  hideCredits = true
